In [45]:
!pip install finance-datareader

Collecting finance-datareader
  Downloading https://files.pythonhosted.org/packages/47/41/00f1387673a5f42034228f541a2650a1c0b87fab8d65363c67df677e2a98/finance_datareader-0.5.0-py3-none-any.whl
Requirement already satisfied: pandas>=0.19.2 in /opt/venv/lib/python3.6/site-packages (from finance-datareader) (0.23.0)
Requirement already satisfied: lxml in /opt/venv/lib/python3.6/site-packages (from finance-datareader) (4.2.1)
Requirement already satisfied: requests-file in /opt/venv/lib/python3.6/site-packages (from finance-datareader) (1.4.3)
Requirement already satisfied: requests>=2.3.0 in /opt/venv/lib/python3.6/site-packages (from finance-datareader) (2.18.4)
Requirement already satisfied: numpy>=1.9.0 in /opt/venv/lib/python3.6/site-packages (from pandas>=0.19.2->finance-datareader) (1.14.3)
Requirement already satisfied: python-dateutil>=2.5.0 in /opt/venv/lib/python3.6/site-packages (from pandas>=0.19.2->finance-datareader) (2.7.3)
Requirement already satisfied: pytz>=2011k in /opt/venv/lib/python3.6/site-packages (from pandas>=0.19.2->finance-datareader) (2018.4)
Requirement already satisfied: six in /opt/venv/lib/python3.6/site-packages (from requests-file->finance-datareader) (1.11.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/venv/lib/python3.6/site-packages (from requests>=2.3.0->finance-datareader) (2018.4.16)
Requirement already satisfied: idna<2.7,>=2.5 in /opt/venv/lib/python3.6/site-packages (from requests>=2.3.0->finance-datareader) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /opt/venv/lib/python3.6/site-packages (from requests>=2.3.0->finance-datareader) (1.22)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /opt/venv/lib/python3.6/site-packages (from requests>=2.3.0->finance-datareader) (3.0.4)
mxnet-cu80 1.1.0 has requirement numpy<=1.13.3, but you'll have numpy 1.14.3 which is incompatible.
Installing collected packages: finance-datareader
Successfully installed finance-datareader-0.5.0

In [46]:
import FinanceDataReader as fdr

df = fdr.DataReader('105560', '2017-01-01', '2017-12-31')
df.head(15)

            Close   Open   High    Low     Volume  Change
Date
2017-01-02  42600  42800  43050  42250   344800.0 -0.0047
2017-01-03  43700  42600  43750  42000   956290.0  0.0258
2017-01-04  44150  43900  44400  43450   831240.0  0.0103
2017-01-05  42800  44200  44200  42550  1070000.0 -0.0306
2017-01-06  42650  43000  43000  42300   710090.0 -0.0035
2017-01-09  42400  42650  42700  42150   784120.0 -0.0059
2017-01-10  43250  43000  43400  42650  1040000.0  0.0200
2017-01-11  43350  42700  43700  42700   912060.0  0.0023
2017-01-12  44100  43600  44100  43350  1010000.0  0.0173
2017-01-13  43850  43500  44300  43400   858380.0 -0.0057
2017-01-16  45150  44100  45250  43950  1440000.0  0.0296
2017-01-17  45850  45300  46100  45100  1220000.0  0.0155
2017-01-18  45800  45400  46000  45100   611830.0 -0.0011
2017-01-19  45550  45400  46200  45400   467430.0 -0.0055
2017-01-20  45400  45300  45850  45300   471930.0 -0.0033